name: Code Quality Checks
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install black==23.1.0 pylint==v2.16.2
    - name: Format check
      run: black -l 100 --diff --check $(git ls-files 'astarte')
    - name: Static code analysis
      run: pylint $(git ls-files 'astarte')
