name: Docs generation for Github Pages

on:
  push:
    branches:
    - 'master'
    - 'release-*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source
      - uses: actions/checkout@v2
        with:
          path: astarte-device-sdk-python
      # Checkout the docs repository
      - uses: actions/checkout@v2
        with:
          repository: astarte-platform/docs
          ssh-key: ${{ secrets.DOCS_DEPLOY_KEY }}
          path: docs
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        working-directory: ./astarte-device-sdk-python/docs
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine requests paho-mqtt cryptography bson PyJWT sphinx m2r2
      - name: Generate Javadocs with Sphinx-doc
        working-directory: ./astarte-device-sdk-python/docs
        run: |
          sphinx-apidoc -f -o . ../astarte
          make html
      - name: Copy Docs
        run: |
          export DOCS_DIRNAME="device-sdks/python/$(echo ${{ github.ref }} | sed 's,refs/heads/,,' | sed 's/master/snapshot/g' | sed 's/release-//g')/api"
          rm -rf docs/$DOCS_DIRNAME
          mkdir -p docs/$DOCS_DIRNAME
          cp -r astarte-device-sdk-python/docs/_build/html/* docs/$DOCS_DIRNAME/
      - name: Commit files
        working-directory: ./docs
        run: |
          git config --local user.email "astarte-machine@ispirata.com"
          git config --local user.name "Astarte Bot"
          git add .
          git commit -m "Update Python SDK documentation"
      - name: Push changes
        working-directory: ./docs
        run: |
          git push origin master
